name: .NET

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Build
      run: For (/R %&I in (*.sln) do dotnet test %%I)
    - name: Test
      run: For /R %%I in (*.sln) do dotnet test %%I

